### ISSUE TITLE
Roadmap to v2.0

### ISSUE THREAD

**Issue by lastsunday** [lastsunday/job-hunting#18]
### Prerelease (v2.X.X)

- [x] Dev framework switch to [WXT](https://github.com/wxt-dev/wxt)
- [x] ContentScript
    - [x] Boss
    - [x] 51job
    - [x] Zhilian
    - [x] Lagou
    - [x] Liepin
- [x] Admin page reactor by react
    - [x] Framework
    - [x] Header
        - [x] Login
        - [x] Statistics
            - [x] Task total
    - [x] DashboardView
    - [x] AssistantView
        - [x] FavoriteJobView
        - [x] FavoriteJobSettingView
        - [x] Pagging
        - [x] Map
        - [x] JobBrowseHistoryView
        - [x] AutoMateView
    - [x] BbsView
        - [x] Issues display
        - [x] Add issue
        - [x] Comment display
        - [x] Add comment
    - [x] Data
        - [x] JobView
            - [x] Search
            - [x] Export
            - [x] Edit tag
        - [x] CompanyView
            - [x] Search
            - [x] Export
            - [x] Edit tag
        - [x] JobTagView
            - [x] Search
            - [x] Add
            - [x] Edit
            - [x] Delete
            - [x] Export
        - [x] CompanyTagView
            - [x] Search
            - [x] Add
            - [x] Edit
            - [x] Delete
            - [x] Export
    - [x] DataSharePlanView
        - [x] Wellcome page
        - [x] Statistics
        - [x] Task
        - [x] Partner
    - [x] SettingView
        - [x] GitHub App Install
        - [x] Backup(Export) & Import
            - [x] Database
            - [x] Job
            - [x] Company
            - [x] JobTag
            - [x] CompanyTag
        - [x] App Info
            - [x] Version&checking
            - [x] How to upgrade app
            - [x] Version desc
            - [x] License
            - [x] Link for home page
            - [x] Link for issues 
- [x] CICD(github action)
- [x] Docs(readme.md,quickstart.md)
